server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-client
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api/client/**
        - id: ms-person
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api/person/**
        - id: ms-pasive
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/pasive/**
        - id: ms-active
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/active/**
        - id: ms-movement
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/movement/**
        - id: ms-payment
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api/payment/**
        - id: ms-transaction
          uri: http://host.docker.internal:8086
          predicates:
            - Path=/api/transaction/**
        - id: ms-parameter
          uri: http://host.docker.internal:8087
          predicates:
            - Path=/api/parameter/**