server:
  port: 8063
  
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/bd_yanki

  kafka:
    bootstrap-servers:  "127.0.0.1:9092"
    consumer:
      group-id: "bootcoin-transfer-yanki_id" 
      
kafka:
  bootstrapAddress: "127.0.0.1:9092"
  topic:
    yanki: "bootcoin-transfer-yanki-topic"
    transactionBootCoin: "bootcoin-transaction-topic"
    transactionYanki: "yanki-transaction-topic"
    paymentYanki: "yanki-payment-topic"
