server:
  port: 8084
  
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/bank
      
app:
  module:
    service:
      url: http://host.docker.internal:8088
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      pasive:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true 