server:
  port: 8071
  
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
      
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/bd_yanki

kafka:
  bootstrapAddress: "host.docker.internal:9092"
  topic:
    payment: "yanki-payment-topic"