server:
  port: 8072
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bd_yanki
  kafka:
    bootstrap-servers:  "localhost:9092"
    consumer:
      group-id: "yanki-payment_id"

kafka:
  bootstrapAddress: "localhost:9092"
  topic:
    payment: "yanki-payment-topic"
    groupId: "yanki-payment_id"
