server:
  port: 8070
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost
    prefer-ip-address: true
    
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bd_yanki